server:
  port: ${SERVER_PORT:8084}

spring:
  application:
    name: payment-notification-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5436/paymentdb}
    username: ${SPRING_DATASOURCE_USERNAME:ticketing}
    password: ${SPRING_DATASOURCE_PASSWORD:ticketing}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:localhost}
    port: ${SPRING_RABBITMQ_PORT:5672}
    username: ${SPRING_RABBITMQ_USERNAME:guest}
    password: ${SPRING_RABBITMQ_PASSWORD:guest}

app:
  rabbitmq:
    exchange: ticketing.events
    confirmed-queue: payment.booking.confirmed.queue
    failed-queue: payment.booking.failed.queue
  security:
    internal-api-key: ${INTERNAL_API_KEY:internal-demo-secret}

management:
  endpoints:
    web:
      exposure:
        include: health,info

springdoc:
  swagger-ui:
    path: /swagger-ui.html
