server:
  port: ${SERVER_PORT:8084}

debug: ${APP_DEBUG:true}

spring:
  config:
    import: optional:file:.env[.properties],optional:file:../.env[.properties]
  application:
    name: payment-notification-service
  datasource:
    url: ${PAYMENT_DB_URL:jdbc:postgresql://ep-morning-meadow-a8vv6di9-pooler.eastus2.azure.neon.tech/paymentdb?&sslmode=require&channelBinding=require}
    username: ${PAYMENT_DB_USERNAME:neondb_owner}
    password: ${PAYMENT_DB_PASSWORD:npg_cd8jbG0HYQnq}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  rabbitmq:
    addresses: ${SPRING_RABBITMQ_ADDRESSES:amqps://jpwpeqpo:Fde1Gvx2RIHSydGr2KMT0XuZVCA9M7ju@yak.lmq.cloudamqp.com/jpwpeqpo}
    username: ${SPRING_RABBITMQ_USERNAME:jpwpeqpo}
    password: ${SPRING_RABBITMQ_PASSWORD:Fde1Gvx2RIHSydGr2KMT0XuZVCA9M7ju}
    virtual-host: ${SPRING_RABBITMQ_VHOST:jpwpeqpo}
    ssl:
      enabled: ${SPRING_RABBITMQ_SSL_ENABLED:true}

app:
  rabbitmq:
    exchange: ticketing.events
    confirmed-queue: payment.booking.confirmed.queue
    failed-queue: payment.booking.failed.queue
    cancelled-queue: payment.booking.cancelled.queue
  security:
    internal-api-key: ${INTERNAL_API_KEY:internal-demo-secret}
  integrations:
    stripe:
      secret-key: ${STRIPE_SECRET_KEY:}
      webhook-secret: ${STRIPE_WEBHOOK_SECRET:}
      currency: ${STRIPE_CURRENCY:usd}
    sendgrid:
      api-key: ${SENDGRID_API_KEY:}
      from-email: ${SENDGRID_FROM_EMAIL:}
      from-name: ${SENDGRID_FROM_NAME:Ticketing}
    twilio:
      account-sid: ${TWILIO_ACCOUNT_SID:}
      auth-token: ${TWILIO_AUTH_TOKEN:}
      from-number: ${TWILIO_FROM_NUMBER:}

management:
  endpoints:
    web:
      exposure:
        include: health,info

springdoc:
  swagger-ui:
    path: /swagger-ui.html
