name: CI Test

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Show workspace
        run: |
          echo "Workflow is running"
          pwd
          ls -la
          echo "Backend folder:"
          ls -la backend || true
          echo "Frontend folder:"
          ls -la frontend || true