server:
  port: ${SERVER_PORT:8081}

spring:
  application:
    name: event-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://ep-long-rice-a8o7biph-pooler.eastus2.azure.neon.tech/eventdb?user=neondb_owner&password=npg_cd8jbG0HYQnq&sslmode=require&channelBinding=require}
    username: ${SPRING_DATASOURCE_USERNAME:neondb_owner}
    password: ${SPRING_DATASOURCE_PASSWORD:npg_cd8jbG0HYQnq}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:localhost}
    port: ${SPRING_RABBITMQ_PORT:5672}
    username: ${SPRING_RABBITMQ_USERNAME:guest}
    password: ${SPRING_RABBITMQ_PASSWORD:guest}

app:
  rabbitmq:
    exchange: ticketing.events

management:
  endpoints:
    web:
      exposure:
        include: health,info

springdoc:
  swagger-ui:
    path: /swagger-ui.html
